# Generated by Django 2.2.9 on 2020-02-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('phonenum', models.CharField(db_column='PhoneNum', max_length=150)),
                ('classifycode', models.CharField(db_column='ClassifyCode', max_length=150)),
                ('clothurl', models.ImageField(db_column='ClothUrl', upload_to='cloth/')),
            ],
            options={
                'managed': True,
                'db_table': 'cloth',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(db_column='PhoneNum', max_length=150)),
                ('stylename', models.CharField(db_column='StyleName', max_length=150)),
            ],
            options={
                'managed': True,
                'db_table': 'style',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phonenum', models.CharField(db_column='PhoneNum', max_length=150, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='UserName', max_length=150)),
                ('password', models.CharField(db_column='Password', max_length=150)),
                ('sex', models.CharField(db_column='Sex', max_length=150)),
                ('requestion', models.CharField(db_column='Requestion', max_length=150)),
                ('answer', models.CharField(db_column='Answer', max_length=150)),
                ('userpic', models.ImageField(db_column='UserPic', default='user/default.jpg', upload_to='user/')),
                ('usermodel', models.CharField(blank=True, db_column='UserModel', max_length=150, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'user',
            },
        ),
    ]
